Homework2: Al Strokov
belovmd/epam-q4-2019 pull request #39
Opened 2019-10-24 09:19 UTC by alstrokov

2019-10-27 20:21 UTC, belovmd requested changes
1. please add tasks description to docstrings
2. Please name PR according our guidelines
3. please address these issues:

2019-10-27 20:21 UTC, belovmd commented on src/task01.py
> +    ditgits.append(num % 10)
please create a reversed number using arithmetic operations

2019-10-27 20:21 UTC, belovmd commented on src/task01.py
> +    if ditgits[:1] != ditgits[-1:]:
please use numbers comparison

2019-10-27 20:21 UTC, belovmd commented on src/task03.py
> +    if not i % 5 and not i % 3:
can we use 15 here?

2019-10-27 20:21 UTC, belovmd commented on src/task04.py
> +    s = str(num)
please avoid magic letters. it's not clear for me names s, c, v

2019-10-27 20:21 UTC, belovmd commented on src/task04.py
> +        rez.append(num % 10)
please don't use lists here. it would be enough to make a number

2019-10-30 11:47 UTC, alstrokov commented
Homework2 updated

2019-11-03 13:43 UTC, belovmd reviewed
7.5

2019-11-03 13:43 UTC, belovmd commented on src/task01.py
> +def isPoly(number):
java naming, not python

2019-11-03 13:43 UTC, belovmd commented on src/task01.py
> +"""Determine if given number is polynome."""
palindrome

2019-11-03 13:43 UTC, belovmd commented on src/task03.py
> +        formatlist[(num % 3 == 0) + 2 * (num % 5 == 0)]))
it looks too complex

2019-11-03 13:43 UTC, belovmd commented on src/task04.py
> +    stringRepresentation = str(num)
''.join(int(el)**2 for el in str(num))

2019-11-03 13:43 UTC, belovmd commented on src/task04.py
> +        for digit in str(number):
can't we use arithmetic operations here?

2019-11-03 13:43 UTC, closed without merging