Homework02
belovmd/epam-q4-2019 pull request #57
Opened 2019-10-31 15:17 UTC by Mantikor

2019-11-03 14:17 UTC, belovmd requested changes
1. wrong PR naming
2. Missed code for external sites tasks
3. no description in  2 files

2019-11-09 15:02 UTC, Mantikor commented
Fixed

2019-11-09 21:07 UTC, belovmd reviewed
6
1. overdue
2. few external tasks
3. issues with code readability

2019-11-09 21:07 UTC, belovmd commented on src/homework02_task4.py
> +    test_list = [test_str[i] for i in range(len(test_str))]
`[char for char in test_str]`?

2019-11-09 21:07 UTC, belovmd commented on src/homework02_task4.py
> +    k = 0
what is k?

2019-11-09 21:07 UTC, belovmd commented on src/homework02_task4.py
> +    2). The program should produce an answer in less than a few seconds.
no decryption method put to docsting

2019-11-09 21:07 UTC, belovmd commented on src/homework02_task4.py
> +            if k != 0:
`if not k`?

2019-11-09 21:07 UTC, belovmd commented on src/homework02_task4.py
> +    position_index = input('Input index for change: ')
`int(input(...))`

2019-11-09 21:07 UTC, closed without merging